### ISSUE TITLE
Investigate interface conversion

### ISSUE THREAD

**Issue by mjpitz** [depscloud/tracker#43]
Came across this looking into a larger use case.

```
panic: interface conversion: interface {} is *schema.Depends, not *schema.Module

goroutine 176 [running]:
github.com/deps-cloud/tracker/pkg/services.(*dependencyService).ListDependents(0xc000070020, 0xb03760, 0xc000228570, 0xc00048d400, 0xc000070020, 0xc000228510, 0x9b40e0)
	/home/travis/gopath/src/github.com/deps-cloud/tracker/pkg/services/service_dependency.go:52 +0x46b
github.com/deps-cloud/api/v1alpha/tracker._DependencyService_ListDependents_Handler(0x9b6c60, 0xc000070020, 0xb03760, 0xc000228570, 0xc00040ee40, 0x0, 0x0, 0x0, 0xc0004027a0, 0x11)
	/home/travis/gopath/pkg/mod/github.com/deps-cloud/api@v0.1.0/v1alpha/tracker/tracker.pb.go:1134 +0x23e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00008aa80, 0xb064e0, 0xc0003d2d80, 0xc00016aa00, 0xc00019e0c0, 0xf1a520, 0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1007 +0x485
google.golang.org/grpc.(*Server).handleStream(0xc00008aa80, 0xb064e0, 0xc0003d2d80, 0xc00016aa00, 0x0)
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1287 +0xe02
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000281e0, 0xc00008aa80, 0xb064e0, 0xc0003d2d80, 0xc00016aa00)
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:722 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:720 +0xa1
```

**Comment by mjpitz** [comment]
Identified the problematic row in the database, although this doesn't speak much to the problem.

```
| depends         | 2/Cjv9BEwBoSTHL3+Du62+8aTrjJXWtQyPnKP/uinwQ | 2/Cjv9BEwBoSTHL3+Du62+8aTrjJXWtQyPnKP/uinwQ |        1 | {"language":"node","version_constraint":"^5.5.7","scopes":["dev"]}                               | depends         | 2/Cjv9BEwBoSTHL3+Du62+8aTrjJXWtQyPnKP/uinwQ | Yp2/OJBBiPvzN7D5SAZ1+iKxRH4x3ELqKLU2oSxuvp8 |        1 | {"language":"node","version_constraint":"4.17.0","scopes":["dev"]}                      |
```

**Comment by mjpitz** [comment]
```
mysql> select * from dts_graphdata where k1 = "2/Cjv9BEwBoSTHL3+Du62+8aTrjJXWtQyPnKP/uinwQ" and k1 = k2 ;
+-----------------+---------------------------------------------+---------------------------------------------+----------+--------------------------------------------------------------------+---------------------+--------------+
| graph_item_type | k1                                          | k2                                          | encoding | graph_item_data                                                    | last_modified       | date_deleted |
+-----------------+---------------------------------------------+---------------------------------------------+----------+--------------------------------------------------------------------+---------------------+--------------+
| depends         | 2/Cjv9BEwBoSTHL3+Du62+8aTrjJXWtQyPnKP/uinwQ | 2/Cjv9BEwBoSTHL3+Du62+8aTrjJXWtQyPnKP/uinwQ |        1 | {"language":"node","version_constraint":"^5.5.7","scopes":["dev"]} | 2020-04-21 02:07:28 | NULL         |
| module          | 2/Cjv9BEwBoSTHL3+Du62+8aTrjJXWtQyPnKP/uinwQ | 2/Cjv9BEwBoSTHL3+Du62+8aTrjJXWtQyPnKP/uinwQ |        1 | {"language":"node","organization":"_","module":"rxjs"}             | 2020-04-21 02:07:28 | NULL         |
+-----------------+---------------------------------------------+---------------------------------------------+----------+--------------------------------------------------------------------+---------------------+--------------+
```

**Comment by mjpitz** [comment]
Seems like it really only happens on the depends data. All in all not too bad. 12 bad data points in 182K

```
mysql> select * from dts_graphdata where k1 = k2 and graph_item_type in ("manages", "depends")
    -> 
    -> ;
+-----------------+---------------------------------------------+---------------------------------------------+----------+----------------------------------------------------------------------------------------------------------+---------------------+---------------------+
| graph_item_type | k1                                          | k2                                          | encoding | graph_item_data                                                                                          | last_modified       | date_deleted        |
+-----------------+---------------------------------------------+---------------------------------------------+----------+----------------------------------------------------------------------------------------------------------+---------------------+---------------------+
| depends         | 0DBb2xWVAk10mrDq6DjZu12CWSliAePdct9IPx1sloE | 0DBb2xWVAk10mrDq6DjZu12CWSliAePdct9IPx1sloE |        1 | {"language":"node","version_constraint":"github:sindresorhus/globby#master","scopes":["dev"]}            | 2020-04-21 02:07:28 | NULL                |
| depends         | 2/Cjv9BEwBoSTHL3+Du62+8aTrjJXWtQyPnKP/uinwQ | 2/Cjv9BEwBoSTHL3+Du62+8aTrjJXWtQyPnKP/uinwQ |        1 | {"language":"node","version_constraint":"^5.5.7","scopes":["dev"]}                                       | 2020-04-21 02:07:28 | NULL                |
| depends         | 2nMmo2BeUuS2xg8r2zsoWcnKin792WiPozJlGhfitnY | 2nMmo2BeUuS2xg8r2zsoWcnKin792WiPozJlGhfitnY |        1 | {"language":"node","version_constraint":"2.x","scopes":["dev"]}                                          | 2020-04-21 01:09:35 | 2020-04-21 01:11:09 |
| depends         | 94h1lTec+H7nub7bkgHTXkCbxx575ugO5MPUpSXAzjo | 94h1lTec+H7nub7bkgHTXkCbxx575ugO5MPUpSXAzjo |        1 | {"language":"node","version_constraint":"next","scopes":["dev"]}                                         | 2020-04-21 01:29:23 | 2020-04-21 01:30:49 |
| depends         | Fx1TlT3zq0TZiPgLNDZLWw+PQmh4vBHnfE+oGXzE6BI | Fx1TlT3zq0TZiPgLNDZLWw+PQmh4vBHnfE+oGXzE6BI |        1 | {"language":"node","version_constraint":"^1.4.0","scopes":["dev"]}                                       | 2020-04-21 01:29:23 | 2020-04-21 01:29:50 |
| depends         | isxvOsDwAulfg3AoXKnNaVGQmHRKFkZXmjq1d55CK8w | isxvOsDwAulfg3AoXKnNaVGQmHRKFkZXmjq1d55CK8w |        1 | {"language":"node","version_constraint":"git://github.com/webdoc/grunt-concat-css.git","scopes":["dev"]} | 2020-04-21 00:42:02 | 2020-04-21 00:49:32 |
| depends         | Os8hwj5UZk9/pTrq09wdN2WccXetlv8qrOarj7K2jwU | Os8hwj5UZk9/pTrq09wdN2WccXetlv8qrOarj7K2jwU |        1 | {"language":"node","version_constraint":"1.4.1","scopes":["dev"]}                                        | 2020-04-21 01:04:40 | 2020-04-21 01:09:35 |
| depends         | taAIJ5373owCe5ZaXUHqCQiSM3EdXeDJw2LQP9PZd4w | taAIJ5373owCe5ZaXUHqCQiSM3EdXeDJw2LQP9PZd4w |        1 | {"language":"node","version_constraint":"^2.9.2","scopes":["dev"]}                                       | 2020-04-21 02:11:55 | NULL                |
| depends         | UoNBKIoAT0UE//ndk/ZzxYWdBpcqVwpO31ABufCw+d8 | UoNBKIoAT0UE//ndk/ZzxYWdBpcqVwpO31ABufCw+d8 |        1 | {"language":"node","version_constraint":"2.0.0","scopes":["dev"]}                                        | 2020-04-21 01:29:23 | 2020-04-21 01:31:38 |
| depends         | XbET4ipiZZMqg8EFcEgh74A/lD70wdAH0ip1LQi40Nk | XbET4ipiZZMqg8EFcEgh74A/lD70wdAH0ip1LQi40Nk |        1 | {"language":"node","version_constraint":"^5.8.0","scopes":["dev"]}                                       | 2020-04-21 01:29:23 | 2020-04-21 01:30:49 |
| depends         | y1VY37SD2WOFt7399jzMGU64bfZWZKMW7XmmCuGDVaA | y1VY37SD2WOFt7399jzMGU64bfZWZKMW7XmmCuGDVaA |        1 | {"language":"node","version_constraint":"^2.2.0","scopes":["dev"]}                                       | 2020-04-21 02:07:28 | 2020-04-21 02:11:53 |
| depends         | Z3WqPcpgiZuJfOnN0m7uj50KdwiFTzJoCD7DYp8v7Xw | Z3WqPcpgiZuJfOnN0m7uj50KdwiFTzJoCD7DYp8v7Xw |        1 | {"language":"node","version_constraint":"^8.2.6","scopes":["dev"]}                                       | 2020-04-21 02:07:28 | 2020-04-21 02:07:44 |
+-----------------+---------------------------------------------+---------------------------------------------+----------+----------------------------------------------------------------------------------------------------------+---------------------+---------------------+
```

Corresponding modules:

```
mysql> select * from dts_graphdata where k1 in (select k1 from dts_graphdata where k1 = k2 and graph_item_type in ("manages", "depends")) and k1 = k2 and graph_item_type in ("module", "source")
    -> ;
+-----------------+---------------------------------------------+---------------------------------------------+----------+--------------------------------------------------------------------------+---------------------+--------------+
| graph_item_type | k1                                          | k2                                          | encoding | graph_item_data                                                          | last_modified       | date_deleted |
+-----------------+---------------------------------------------+---------------------------------------------+----------+--------------------------------------------------------------------------+---------------------+--------------+
| module          | 0DBb2xWVAk10mrDq6DjZu12CWSliAePdct9IPx1sloE | 0DBb2xWVAk10mrDq6DjZu12CWSliAePdct9IPx1sloE |        1 | {"language":"node","organization":"_","module":"globby"}                 | 2020-04-21 02:07:28 | NULL         |
| module          | 2/Cjv9BEwBoSTHL3+Du62+8aTrjJXWtQyPnKP/uinwQ | 2/Cjv9BEwBoSTHL3+Du62+8aTrjJXWtQyPnKP/uinwQ |        1 | {"language":"node","organization":"_","module":"rxjs"}                   | 2020-04-21 02:07:28 | NULL         |
| module          | 2nMmo2BeUuS2xg8r2zsoWcnKin792WiPozJlGhfitnY | 2nMmo2BeUuS2xg8r2zsoWcnKin792WiPozJlGhfitnY |        1 | {"language":"node","organization":"_","module":"eslint-plugin-import"}   | 2020-04-21 02:12:01 | NULL         |
| module          | 94h1lTec+H7nub7bkgHTXkCbxx575ugO5MPUpSXAzjo | 94h1lTec+H7nub7bkgHTXkCbxx575ugO5MPUpSXAzjo |        1 | {"language":"node","organization":"_","module":"typescript"}             | 2020-04-21 02:13:25 | NULL         |
| module          | Fx1TlT3zq0TZiPgLNDZLWw+PQmh4vBHnfE+oGXzE6BI | Fx1TlT3zq0TZiPgLNDZLWw+PQmh4vBHnfE+oGXzE6BI |        1 | {"language":"node","organization":"_","module":"babel-preset-env"}       | 2020-04-21 02:12:55 | NULL         |
| module          | isxvOsDwAulfg3AoXKnNaVGQmHRKFkZXmjq1d55CK8w | isxvOsDwAulfg3AoXKnNaVGQmHRKFkZXmjq1d55CK8w |        1 | {"language":"node","organization":"_","module":"grunt-concat-css"}       | 2020-04-21 00:49:33 | NULL         |
| module          | Os8hwj5UZk9/pTrq09wdN2WccXetlv8qrOarj7K2jwU | Os8hwj5UZk9/pTrq09wdN2WccXetlv8qrOarj7K2jwU |        1 | {"language":"node","organization":"_","module":"unorm"}                  | 2020-04-21 02:11:55 | NULL         |
| module          | taAIJ5373owCe5ZaXUHqCQiSM3EdXeDJw2LQP9PZd4w | taAIJ5373owCe5ZaXUHqCQiSM3EdXeDJw2LQP9PZd4w |        1 | {"language":"node","organization":"_","module":"bluebird"}               | 2020-04-21 02:11:55 | NULL         |
| module          | UoNBKIoAT0UE//ndk/ZzxYWdBpcqVwpO31ABufCw+d8 | UoNBKIoAT0UE//ndk/ZzxYWdBpcqVwpO31ABufCw+d8 |        1 | {"language":"node","organization":"_","module":"tslint-plugin-prettier"} | 2020-04-21 02:12:58 | NULL         |
| module          | XbET4ipiZZMqg8EFcEgh74A/lD70wdAH0ip1LQi40Nk | XbET4ipiZZMqg8EFcEgh74A/lD70wdAH0ip1LQi40Nk |        1 | {"language":"node","organization":"_","module":"tslint"}                 | 2020-04-21 02:12:58 | NULL         |
| module          | y1VY37SD2WOFt7399jzMGU64bfZWZKMW7XmmCuGDVaA | y1VY37SD2WOFt7399jzMGU64bfZWZKMW7XmmCuGDVaA |        1 | {"language":"node","organization":"_","module":"fast-glob"}              | 2020-04-21 02:11:55 | NULL         |
| module          | Z3WqPcpgiZuJfOnN0m7uj50KdwiFTzJoCD7DYp8v7Xw | Z3WqPcpgiZuJfOnN0m7uj50KdwiFTzJoCD7DYp8v7Xw |        1 | {"language":"node","organization":"_","module":"babel-eslint"}           | 2020-04-21 02:13:25 | NULL         |
+-----------------+---------------------------------------------+---------------------------------------------+----------+--------------------------------------------------------------------------+---------------------+--------------+
12 rows in set (0.19 sec)
```

**Comment by mjpitz** [comment]
So I found it really interesting that this was happening to node modules. Using that list of affected edges, I was able to track the issue back to repositories where the node_modules directory was being commit to the repo. As a result, the extractor matches on the module and its added. Looking at the resolved package.json in a node_modules directory, you can see that the package itself is listed as a dependency. For example, the following snippet is from the resolved unorm package.json:

```
  "devDependencies": {
    "benchmark": "~1.0.0",
    "grunt": "~0.4.1",
    "grunt-contrib-jshint": "~0.8.0",
    "grunt-contrib-watch": "~0.5.0",
    "grunt-simple-mocha": "~0.4.0",
    "unorm": "1.4.1"
  },
```

This results in a self-referential edge in the database which breaks this query.

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgQVtlc2xpbnRdIC0tPnxkZXZ8IEFcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgQVtlc2xpbnRdIC0tPnxkZXZ8IEFcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

A few soft proposals here:
1. extraction of these dependencies can be improved by filtering out any known subpaths. eg, the package.json extractor can filter out node_modules, etc.
1. storage of edges can be prevented through a simple addition to the SourceService#getProposed method to filter out dependencies whose "k1 == k2"
1. query for these cases can be prevented by adding a target node type, but that does complicate the query logic

I'm going to opt for making change 1 and 2. Together they should sufficiently cover the fix.

**Comment by mjpitz** [comment]
Wound up opting for 3 because the other two were only partial solutions to the problem.
